version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: gochamba_db
      DATABASE_URL: "postgresql://usuario:admin123@localhost:5433/gochamba_db"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
